# Top of file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout # Checks out the source code
      - run: python hw.py
      - run: echo "Hello World!"